PerfExplore: Add the first cut of Flux PerfExplore
flux-framework/flux-scalability pull request #4
Opened 2016-09-15 22:53 UTC by dongahn

Add the first set of scripts, collectively called Flux PerfExplore:

- README.md documents the overall description of this tester
- The commit message of perfexplore.sh and ached-scale-wrap.sh describes the usage with `--help` option
- Extend sharness so that the test results can be printed in TAP

2016-09-15 22:54 UTC, dongahn commented
@trws and @tpatki: Here is the first cut of Flux PerfExplore. I can hold on to this for ever to polish it but I realized merging a reason version into the repo can facilitate working w/ @tpatki. Appreciate if you can review this PR. Thanks!

2016-09-19 23:54 UTC, trws commented on t/perfexplore.sh
> +    echo <&2 "usage: ${SCRIPT_NM} [OPTIONS] FLUX_PATH|EXP_ID"
So, I realize this is entirely stylistic, but do you have something against a heredoc for these?  I find it a little easier to read with just a single cat command than all of the echos personally.

2016-09-19 23:58 UTC, trws commented on t/perfexplore.sh
> +            dep_id=$(msub -V -l ${spec} sched-scale-wrap.sh)
Is msub globally available? For some reason I thought we only had sbatch in a few places.

2016-09-20 00:01 UTC, trws approved these changes
Overall, this looks like a good start.  I'm not entirely clear on whether this is a scheduler test suite or an overall throughput test suite, but it definitely covers a number of cases we need to cover.  There are a few things I think we'll want/need in addition to this, such as having a few default parameter sets we can build into something like the makefile to automate use and so-forth, but this seems like a good place to start overall.

My one quibble really is that it would be nice to have something other than msub as an option, so you could for example salloc and then use job steps or similar, but again that's an enhancement rather than a requirement.

2016-09-20 00:05 UTC, dongahn commented
> Overall, this looks like a good start. I'm not entirely clear on whether this is a scheduler test suite or an overall throughput test suite, but it definitely covers a number of cases we need to cover. There are a few things I think we'll want/need in addition to this, such as having a few default parameter sets we can build into something like the makefile to automate use and so-forth, but this seems like a good place to start overall.

Thanks @trws. Yes the idea is to continue to grow this to cover many perf/scal space, not only for sched but also for core. 

Completely agreed on the default set. Will put that as a separate issue. 

> My one quibble really is that it would be nice to have something other than msub as an option, so you could for example salloc and then use job steps or similar, but again that's an enhancement rather than a requirement.

Intent is to continue to port this to not only slurm but also other native resource manager, and the option for the driver is a placeholder for that one. Another issue to create.

2016-09-20 00:06 UTC, dongahn commented on t/perfexplore.sh
> +    echo <&2 "usage: ${SCRIPT_NM} [OPTIONS] FLUX_PATH|EXP_ID"
Sure. Not a problem to convert his this to here doc.

2016-09-20 00:08 UTC, dongahn commented on t/perfexplore.sh
> +            dep_id=$(msub -V -l ${spec} sched-scale-wrap.sh)
sbatch is not supported in the first cut; only msub. Like I said below, a new native workload manager is easy to be added...

2016-09-20 01:20 UTC, dongahn commented on t/perfexplore.sh
> +    echo <&2 "usage: ${SCRIPT_NM} [OPTIONS] FLUX_PATH|EXP_ID"
OK. I forced a push. Let me know if there is anything else you want me to address in this PR. thanks!

2016-09-20 01:24 UTC, dongahn commented on t/perfexplore.sh
> +            dep_id=$(msub -V -l ${spec} sched-scale-wrap.sh)
Sorry, I think i misread your note. I think you are asking whether LC has some machines on which only sbatch is supported. I don't know the answer to this question. @lipari can chime in. Like I said, adding sbatch isn't difficult at all if this becomes a roadblock  (in particular sbatch has the one-to-one mapping of options of MOAB).

2016-09-20 20:11 UTC, lipari commented on t/perfexplore.sh
> +            dep_id=$(msub -V -l ${spec} sched-scale-wrap.sh)
Of the two, `msub` is the more universal on LC systems.  On Slurm-scheduled systems, we'll have an `msub` wrapper that invokes sbatch under the covers.  However, on Moab-scheduled systems, using sbatch will not be allowed.

2016-09-20 20:17 UTC, lipari commented on t/README.md
> +     or "true false");
It's not immediately obvious to me what "scheduling delay" means, and seeing the "true false" option makes it doubly confusing.

2016-09-20 20:20 UTC, lipari commented on t/README.md
> +Here, `integer.integer` is the unique experiment ID (`EXP_ID`) with which
What is the integer.integer made up of?  A time stamp?  A hash of the experimental parameters?  Or some randomly generated number?

2016-09-20 20:24 UTC, lipari commented on t/README.md
> +- **Flux Job Counts**: Flux job counts to explore;
I think of job counts as including two dimensions:  running jobs and queued jobs.  Perhaps you could clarify which of these (or both combined) you are testing.

2016-09-20 20:26 UTC, lipari requested changes
I'm going to continue to explore this PR in more detail, but thought I'd issue my comments now on the README

2016-09-20 20:29 UTC, dongahn commented on t/README.md
> +     or "true false");
This is the new scheduling optimization option but i can see why it is confusing. will revise.

2016-09-20 20:31 UTC, dongahn commented on t/README.md
> +- **Flux Job Counts**: Flux job counts to explore;
This is the total number of jobs you submit to each instance. Will revise.

2016-09-20 20:32 UTC, dongahn commented on t/README.md
> +Here, `integer.integer` is the unique experiment ID (`EXP_ID`) with which
first interger: epoch since the reference time (date %s)
second integer: random number

so that each can be reasonably ordered. Will revise.

Thank you so much for the review Don!

2016-09-20 22:12 UTC, dongahn commented
@lipari: Ok all the changes pushed.

2016-09-20 22:21 UTC, lipari approved these changes

2016-09-20 22:22 UTC, merged